[versions]
assertj = "3.27.6"
jackson = "2.20.1"
spotbugs = "4.9.8"
wiremock = "3.13.2"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
wiremock = { module = "org.wiremock:wiremock", version.ref = "wiremock" }
